### ISSUE TITLE
Update compatibility note

### ISSUE THREAD

**Issue by acrylian** [ArnaudHocevar/ZPGoogleAnalytics20#1]
Please update the note as it is not compatible with Zenphoto and there is no version 2.0 at all. Thanks.

![bildschirmfoto 2015-10-25 um 09 46 37](https://cloud.githubusercontent.com/assets/2474309/10714769/d46435aa-7afd-11e5-9677-83609e624931.jpg)

**Comment by ArnaudHocevar** [comment]
Fixed.
